apiVersion: apps/v1
kind: Deployment
metadata:
  name: compredictprod
  namespace: flux-system
  labels:
    name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: compredictprod
  replicas: 1
  template:
    metadata:
      labels:
        app: compredictprod
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - Production
              weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - compredictdemoprod
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
              protocol: TCP
