apiVersion: apps/v1
kind: Deployment
metadata:
  name: compredictprod
  namespace: banana-app-demo
  labels:
    name: banana-deploy
spec:
  selector:
    matchLabels:
      app: banana
  replicas: 1
  template:
    metadata:
      labels:
        app: banana
    spec:
      containers:
      - name: banana-app
        image: hashicorp/http-echo
        imagePullPolicy: Always
        args:
        - "-text=banana"