apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappprod
  namespace: flux-system
  labels:
    app: apache-app
spec:
  selector:
    matchLabels:
      app: apache-app
  replicas: 3
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - name: apache-container
        image: avian19/apache-ne:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
