apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappprod
  namespace: flux-system
  labels:
    name: demoappprod-deploy
spec:
  selector:
    matchLabels:
      name: demoappprod
  replicas: 3
  template:
    metadata:
      labels:
        name: demoappprod
    spec:
      containers:
      - name: apache-container
        image: avian19/apache-ne:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
