apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoappprod
spec:
  ingressClassName: nginx # ingress-nginx specifix
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demoappprod
            port:
              number: 80
