apiVersion: v1
kind: Service
metadata:
  name: compredictprod
  namespace: banana-app-demo
  labels:
    name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image
