apiVersion: v1
kind: Service
metadata:
  name: compredictprod
  namespace: flux-system
  labels:
    name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: compredictprod
  ports:
    - port: 80 # Default port for image
      targetPort: 8085
      protocol: TCP
