apiVersion: apps/v1
kind: Deployment
metadata:
  name: compredictstage
  namespace: flux-system
  labels:
    name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: compredictstage
  replicas: 1
  template:
    metadata:
      labels:
        app: compredictstage
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80