apiVersion: v1
kind: Service
metadata:
  name: compredictstage
  namespace: flux-system
  labels:
    name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: compredictstage
  ports:
    - port: 80 # Default port for image
      targetPort: 8085
      protocol: TCP
