apiVersion: v1
kind: Service
metadata:
  name: nginxsvcstage
  namespace: flux-system
  labels:
    name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30081
      name: http
    - port: 443
      nodePort: 30444
      name: https
  selector:
    app: nginxpod